FROM amd64/ubuntu:14.04

RUN apt-get update && apt-get install -y libc6 libncurses5 libstdc++6 libevent-dev \
    libevent-pthreads-2.0-5 libcrypto++9 libssl1.0.0 libmysqlcppconn7 \
    libtcmalloc-minimal4 libjsoncpp0 libjsoncpp0 traceroute bwm-ng autoconf \
    gdb netcat iftop vim netcat mysql-client-core-5.5 gcc g++ make python cpp cpp-4.8 gcc-4.8 g++-4.8 \
    gcc-4.8-multilib g++-4.8-multilib libmsgpack-dev libjsoncpp-dev libmysqlcppconn-dev \
    libgtest-dev cmake3 libgoogle-perftools-dev libssl-dev \
    libmysqlclient-dev libcrypto++-dev git binutils uuid-dev libtool wget python-pip \
    check libpcre3-dev autoconf pkg-config ninja-build python3-pip python3.5

RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib/ && cd .. && rm -rf gtest
RUN ln -s /usr/lib/libtcmalloc_minimal.so.4 /usr/lib/libtcmalloc_minimal.so.0

RUN rm -rf /var/lib/{apt,dpkg,cache,log}/

#RUN pip install lmake==1.0.11

RUN apt-get install -y llvm

# autoconf
# RUN wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz -O /tmp/openssl.tar.gz && cd /tmp \
#       && tar xf openssl.tar.gz && cd openssl-1.1.1c && setarch i386 ./config -m32 && make -j4 && make install \
#       && cd /tmp && rm -rf openssl-1.1.1c && rm openssl.tar.gz

# RUN cd /usr/src && wget https://www.bullseye.com/download/BullseyeCoverage-8.15.11-Linux-x64.tar \
#  && tar xvf BullseyeCoverage-8.15.11-Linux-x64.tar && cd BullseyeCoverage-8.15.11 \
#  && ./install --prefix /opt/BullseyeCoverage --key 3VPypR0MACbL1ZYRX30n4fXr0cRJfb3EpeQd \
#  && cd .. && rm -rf BullseyeCoverage-8.15.11/ && rm BullseyeCoverage-8.15.11-Linux-x64.tar
#
# ENV PATH="/opt/BullseyeCoverage/bin:${PATH}"

VOLUME /data
WORKDIR /data

