FROM parkeeron/build_nginx:1.0

RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y build-essential libtool libpcre3 libpcre3-dev \
    zlib1g-dev

RUN rm -rf /var/lib/{apt, dpkg, cache, log}/
